<?php

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group_content_menu\GroupContentMenuInterface;
use Drupal\group_content_submenu\GroupContentSubmenuInsert;
use Drupal\group_content_submenu\GroupContentSubmenuAlter;
use Drupal\group_content_submenu\ShadowlinkHelper;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function group_content_submenu_group_content_menu_presave(GroupContentMenuInterface $gcm) {
  \Drupal::classResolver(ShadowlinkHelper::class)
    ->groupContentMenuPresave($gcm);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function group_content_submenu_field_config_insert(FieldConfigInterface $field_config) {
  GroupContentSubmenuInsert::fieldConfig($field_config);
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function group_content_submenu_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  \Drupal::classResolver(GroupContentSubmenuAlter::class)
    ->widget($element, $form_state, $context);
}

